### ISSUE TITLE
Inflation problem

### ISSUE THREAD

**Issue by cesards** [romainpiel/Michelangelo#1]
Hi @RomainPiel I had a look to your library and looks great. I just started with Butterknife a few weeks ago and I'm in love, and combined with your lib would be perfect. However I've reviewed your code and you don't support View Inflation into a viewgroup. You should read this article (it's very good) and let support that :-)

http://www.doubleencore.com/2013/05/layout-inflation-as-intended/

Thanks!

**Comment by romainpiel** [comment]
Hi @m3n0R thanks for your feedback.

I'm afraid this is off scope because I'm already inflating the layout into a ViewGroup. See the line:

``` java
View.inflate(context, layoutResId, view);
```

(https://github.com/RomainPiel/Michelangelo/blob/master/michelangelo/src/main/java/com/romainpiel/michelangelo/Michelangelo.java#L35)

This is exactly the same as writing:

``` java
layoutInflater.inflate(layoutResId, view);
```

And given that `view` cannot be null (I create it the line before), it's the same as writing:

``` java
layoutInflater.inflate(layoutResId, view, true);
```

Now, what Michelangelo does?
- it creates a `ViewGroup` for the specified class
- it inflates the given layout in it

That's why I recommend using `<merge>` as a root of your layout xml and tweak your layout params in your ViewGroup Java code. If you really want to have a more fancy root, the associated layout attributes will be taken in account.

Michelangelo is heavily inspired by AndroidAnnotations `@EViewGroup`, have a look at its doc:
https://github.com/excilys/androidannotations/wiki/Enhance%20custom%20views

Feel free to fork the library and change it to suit your needs.

**Comment by cesards** [comment]
Ok, perfect. Thanks!
