### ISSUE TITLE
What is wrong with Android Annotations

### ISSUE THREAD

**Issue by alexandru-calinoiu** [romainpiel/Michelangelo#2]
Hi,

Great project, but why is this better than android annotations and their view/layout injection.

**Comment by romainpiel** [comment]
Hey,

AndroidAnnotations is awesome, it's pretty powerful but I'm not really into pre-compiler libraries.
I actually based one of my previous apps on AndroidAnnotations and the biggest issues I had were:
- pre-compiler slowing down the build process (in case of big projects)
- too strong dependency to a library. I like smaller dependencies so it doesn't screw up the whole project when something's wrong
- clunky integration with gradle (I haven't tested lately though)

Anyway, there are great part about it as well! Since I used AA, I keep making custom views (it makes things much cleaner). So I made Michelangelo to have the power of annotations with something rather small.

**Comment by romainpiel** [comment]
@balauru I guess I can close this ticket
